import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchDictionary } from './languageAPI';

const initialState = {
  dictionary: {},
  language: 'hun',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const loadDictionary = createAsyncThunk(
  'language/loadDictionary',
  async (language) => {
    const response = await fetchDictionary(language);
    console.log(response);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const languageSlice = createSlice({
  name: 'counter',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setLanguage: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.language = action.payload;
    },
    setDictionary: (state, action) => {
      state.dictionary = action.payload;
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      // .addCase(loadDictionary.pending, (state) => {
        // state.status = 'loading';
      // })
      .addCase(loadDictionary.fulfilled, (state, action) => {
        // state.status = 'idle';
        state.dictionary = action.payload;
      });
  },
});

export const { setLanguage, setDictionary } = languageSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectDictionary = (state) => state.language.dictionary;
export const selectLanguage = (state) => state.language.language;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount) => (dispatch, getState) => {
//   const currentValue = selectCount(getState());
//   if (currentValue % 2 === 1) {
//     dispatch(incrementByAmount(amount));
//   }
// };

export default languageSlice.reducer;
